- .framgia-ci.yml
- app/assets/javascripts/custom.js
- app/assets/javascripts/home.js
- app/assets/javascripts/order.js
- app/assets/stylesheets/custom.scss
- app/assets/stylesheets/home.scss
- app/controllers/concerns/admin_load_order.rb
- app/models/dish.rb
- app/models/order.rb
- app/models/supports/admin_order.rb
- app/models/supports/combo.rb
- app/models/supports/dish.rb
- app/models/supports/order.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20170313013315_create_dishes.rb
- db/schema.rb
- db/seeds.rb
- rails_best_practices.yml
> Manage order

- .rubocop.yml
- app/assets/stylesheets/custom.scss
- app/assets/stylesheets/home.scss
- app/assets/stylesheets/order_combos.scss
- app/controllers/guests_controller.rb
- app/controllers/orders_controller.rb
- app/models/ability.rb
- app/models/concerns/encode.rb
- app/views/combos/_combo.html.erb
- app/views/combos/_search.html.erb
- app/views/combos/index.html.erb
- app/views/combos/index.js.erb
- app/views/orders/_ordering_cart.html.erb
- app/views/orders/show.html.erb
- config.reek
- config/locales/en.yml
- spec/controllers/order_combos_controller_spec.rb
> fix homepage + order

- app/assets/javascripts/custom.js
- app/assets/stylesheets/custom.scss
- app/assets/stylesheets/modal.scss
- app/controllers/admin/orders_controller.rb
- app/controllers/orders_controller.rb
- app/helpers/admin/order_helper.rb
- app/models/ability.rb
- app/models/concerns/encode.rb
- app/models/discount_code.rb
- app/models/order.rb
- app/models/order_combo.rb
- app/views/admin/orders/_discount_row.html.erb
- app/views/admin/orders/_modal.html.erb
- app/views/admin/orders/_order.html.erb
- app/views/admin/orders/show.html.erb
- config/locales/en.yml
- db/migrate/20170623065341_create_discount_codes.rb
> fix homepage + add discount_code

- app/assets/javascripts/order_admin.js
- app/assets/stylesheets/admin_combos.scss
- app/assets/stylesheets/custom.scss
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/concerns/admin_load_order.rb
- app/views/admin/order_combos/_order_combo_item.html.erb
- app/views/admin/order_dishes/_order_dish_item.html.erb
- app/views/admin/orders/_add_order_item.html.erb
- app/views/admin/orders/_modal_save_order.html.erb
- app/views/admin/orders/_order_info.html.erb
- app/views/admin/orders/_order_item.html.erb
- app/views/admin/orders/show.html.erb
- config/locales/en.yml
> fix order detail

- app/assets/javascripts/discount.js
- app/assets/stylesheets/discount.scss
- app/controllers/admin/discount_codes_controller.rb
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/concerns/admin_load_order.rb
- app/models/discount_code.rb
- app/models/supports/discount_code.rb
- app/views/admin/discount_codes/_item_discount_code.html.erb
- app/views/admin/discount_codes/_modal_edit.erb
- app/views/admin/discount_codes/index.html.erb
- app/views/admin/discount_codes/index.js.erb
- app/views/admin/order_combos/_order_combo_item.html.erb
- app/views/admin/order_dishes/_order_dish_item.html.erb
- app/views/combos/_combo.html.erb
- app/views/dishes/_dish.html.erb
- app/views/layouts/_menu_admin.html.erb
- config/locales/en.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20170623065341_create_discount_codes.rb
> Manage discount

- app/controllers/admin/categories_controller.rb
- app/controllers/admin/combos_controller.rb
- app/models/category.rb
- app/models/supports/category.rb
- app/views/admin/categories/_category.html.erb
- app/views/admin/categories/_form.html.erb
- app/views/admin/categories/edit.html.erb
- app/views/admin/categories/index.html.erb
- app/views/admin/categories/index.js.erb
- app/views/admin/categories/new.html.erb
- app/views/admin/categories/show.html.erb
- app/views/admin/combos/index.js.erb
- app/views/layouts/_menu_admin.html.erb
- db/schema.rb
> Admin category

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/channels/application_cable.rb
- app/assets/javascripts/channels/channel.rb
- app/assets/javascripts/channels/messages_channel.rb
- app/assets/javascripts/messages.js
- app/assets/stylesheets/custom.scss
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/models/order_combo.rb
- app/models/order_dish.rb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20170313013910_create_order_dishes.rb
- db/migrate/20170413065341_create_order_combos.rb
- db/schema.rb
> Notification

- .eslintignore
- .scss-lint.yml
- app/assets/javascripts/custom.js
- app/assets/javascripts/jquery.timepicker.js
- app/assets/stylesheets/custom.scss
- app/assets/stylesheets/jquery.timepicker.css
- app/controllers/tables_controller.rb
- app/models/table.rb
- app/views/layouts/application.html.erb
- app/views/tables/_reservation.html.erb
- db/migrate/20170706061547_change_column_time_in.rb
- db/schema.rb
> Fix booking

- app/helpers/session_helper.rb
- spec/factories/guests.rb
- spec/helpers/admin/order_helper_spec.rb
- spec/helpers/session_helper_spec.rb
- spec/models/guest_spec.rb
> rspec helpers, fixguest_spec_model

- app/views/tables/_map.html.erb
- app/views/tables/_reservation.html.erb
- app/views/tables/index.html.erb
- config/locales/en.yml
- spec/features/booking/fill_booking_spec.rb
- spec/features/combos/filter_combo_spec.rb
- spec/features/combos/search_combo_spec.rb
- spec/features/dishes/filter_dish_spec.rb
- spec/features/dishes/search_dish_spec.rb
- spec/features/orders/check_order_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/views/layouts/application_spec.rb
- spec/views/orders/index_spec.rb
- spec/views/pages/home_spec.rb
> Integration test for pages, dishes, combos, booking

- app/assets/javascripts/promo.js
- app/assets/stylesheets/custom.scss
- app/controllers/admin/categories_controller.rb
- app/controllers/admin/combos_controller.rb
- app/controllers/admin/dishes_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/order_combos_controller.rb
- app/controllers/order_dishes_controller.rb
- app/helpers/session_helper.rb
- app/views/admin/orders/_order.html.erb
- app/views/orders/show.html.erb
- config/locales/en.yml
> fix some err

- .framgia-ci.yml
- .gitignore
- .rubocop.yml
- .rubocop_disabled.yml
- .rubocop_enabled.yml
- app/controllers/admin/categories_controller.rb
- app/controllers/admin/combos_controller.rb
- app/controllers/admin/dishes_controller.rb
- app/views/admin/categories/index.html.erb
- config.reek
- spec/features/admin/admin_categories_spec.rb
- spec/features/admin/admin_combos_spec.rb
- spec/features/admin/admin_discount_codes_spec.rb
- spec/features/admin/admin_logins_spec.rb
- spec/features/admin/admin_profile_spec.rb
- spec/features/admin/admin_users_spec.rb
> Integration admin test

- app/views/admin/bills/_bill.html.erb
- app/views/admin/bills/show.html.erb
- app/views/admin/categories/show.html.erb
- app/views/admin/chef/_form_combo_cooking.html.erb
- app/views/admin/chef/_form_combo_needing.html.erb
- app/views/admin/chef/_form_dish_needing.html.erb
- app/views/admin/chef/index.html.erb
- app/views/admin/combos/show.html.erb
- app/views/admin/discount_codes/_item_discount_code.html.erb
- app/views/admin/discount_codes/index.html.erb
- app/views/admin/dishes/show.html.erb
- app/views/admin/order_combos/_form.html.erb
- app/views/admin/order_dishes/_form.html.erb
- app/views/admin/orders/_form.html.erb
- app/views/admin/orders/_modal.html.erb
- app/views/admin/orders/_modal_save_order.html.erb
- app/views/admin/orders/_order.html.erb
- app/views/admin/orders/_order_info.html.erb
- app/views/admin/orders/_order_item.html.erb
- app/views/admin/orders/_order_item_current.html.erb
- app/views/admin/orders/_order_item_footer.html.erb
- app/views/admin/orders/show.html.erb
- app/views/admin/promos/_promo.html.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/index.html.erb
- app/views/admin/users/new.html.erb
> refactor for devise view-2

- app/controllers/admin/category_dishes_controller.rb
- app/controllers/admin/combo_dishes_controller.rb
- app/controllers/orders_controller.rb
- app/views/admin/categories/show.html.erb
- app/views/admin/combos/show.html.erb
- app/views/pages/_book_table_online.html.erb
- config/locales/en.yml
- config/routes.rb
> fix category combo in admin( delete bug)

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- config/environments/development.rb
- config/i18n-js.yml
- config/locales/en.yml
> init i18njs

- .eslintrc.json
- app/controllers/admin/categories_controller.rb
- app/controllers/admin/chef_controller.rb
- app/controllers/admin/combos_controller.rb
- app/controllers/admin/discount_codes_controller.rb
- app/controllers/admin/dishes_controller.rb
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/promos_controller.rb
- app/controllers/admin/staffs_controller.rb
- app/models/ability.rb
- app/models/order.rb
- app/models/order_combo.rb
- app/models/order_dish.rb
- app/models/supports/order_support.rb
- config/routes.rb
> fix authorize ability, userscontroller -> staffscontroller

- app/assets/javascripts/channels/messages.js
- app/assets/javascripts/order.js
- app/assets/javascripts/order_admin.js
- app/channels/application_cable/connection.rb
- app/views/admin/chef/_form_combo_cooking.html.erb
- app/views/admin/chef/_form_combo_needing.html.erb
- app/views/admin/chef/_form_dish_cooking.html.erb
- app/views/admin/chef/_form_dish_needing.html.erb
- app/views/admin/orders/_order.html.erb
- app/views/admin/orders/index.html.erb
- app/views/admin/staffs/edit.html.erb
- app/views/admin/staffs/index.html.erb
- app/views/admin/staffs/new.html.erb
- app/views/layouts/_menu_staff.html.erb
> real-time order page

- app/assets/javascripts/custom.js
- app/assets/stylesheets/color.scss
- app/assets/stylesheets/custom.scss
- app/controllers/admin/orders_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/tables_controller.rb
- app/models/ability.rb
- app/models/order.rb
- app/models/supports/order_support.rb
- app/models/table.rb
- app/views/admin/orders/_order.html.erb
- app/views/admin/orders/_order_content.html.erb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/index.js.erb
- app/views/admin/orders/update.js.erb
- app/views/layouts/_menu_staff.html.erb
- app/views/orders/show.html.erb
- config/locales/en.yml
- spec/factories/orders.rb
- spec/jobs/message_broadcast_job_spec.rb
- spec/models/order_combo_spec.rb
- spec/models/order_spec.rb
- spec/models/supports/order_spec.rb
- spec/models/table_spec.rb
> update view, ajax rails, filter, performer view index order, validate table

- .eslintignore
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/concerns/load_order.rb
- app/controllers/order_combos_controller.rb
- app/controllers/order_dishes_controller.rb
- app/controllers/orders_controller.rb
- app/helpers/session_helper.rb
- app/models/concerns/encode.rb
- app/models/order.rb
- app/models/order_combo.rb
- app/models/order_dish.rb
- app/models/table.rb
- config.reek
- config/locales/en.yml
- config/routes.rb
> edit order combos, dish orders controller

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/custom.js
- app/assets/javascripts/order.js
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/order_dishes_controller.rb
- app/views/admin/orders/_form.html.erb
- app/views/admin/orders/_order_content.html.erb
- app/views/layouts/_cart_text.html.erb
- app/views/orders/_cart_row.html.erb
- app/views/orders/_cart_row_combo.html.erb
- app/views/orders/_ordering_cart.html.erb
- app/views/orders/show.html.erb
> view after edit controller

- Gemfile
- Gemfile.lock
- app/assets/javascripts/dashboard.js
- app/controllers/admin/dashboards_controller.rb
- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/views/admin/dashboards/_chart.html.erb
- app/views/admin/dashboards/_statistic.html.erb
- app/views/admin/dashboards/index.html.erb
- app/views/layouts/_menu_staff.html.erb
- config/locales/en.yml
- config/routes.rb
- config/routes/api.rb
- db/seeds.rb
- spec/factories/order_combos.rb
- spec/factories/orders.rb
- spec/factories/staffs.rb
> Update seeds + init chart

- app/controllers/admin/order_combos_controller.rb
- app/controllers/admin/order_dishes_controller.rb
- app/controllers/combos_controller.rb
- app/controllers/dishes_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/rater_controller.rb
- app/helpers/session_helper.rb
- app/models/average_cache.rb
- app/models/combo.rb
- app/models/customer.rb
- app/models/dish.rb
- app/models/overall_average.rb
- app/models/rate.rb
- app/models/rating_cache.rb
- app/views/combos/show.html.erb
- app/views/dishes/show.html.erb
- app/views/orders/_cart_row.html.erb
- app/views/orders/_cart_row_combo.html.erb
- app/views/orders/_rate.html.erb
- app/views/orders/show.html.erb
+ init ratyrate model, controller, view
+ edit view show dish, show order of customer
> init ratyrate model, controller, view

- app/controllers/admin/bills_controller.rb
- app/controllers/admin/membership_coupons_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/xml_controller.rb
- app/models/bill.rb
- app/models/bill_detail.rb
- app/models/customer.rb
- app/models/membership_coupon.rb
- app/models/order.rb
- app/models/supports/membership_coupon_support.rb
- config/locales/en.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20170720122943_create_membership_coupons.rb
- db/migrate/20170801022016_add_colunm_money_paid_to_customers.rb
- db/migrate/20170801022433_add_colunm_discount_to_bills.rb
- db/schema.rb
- spec/controllers/sessions_controller_spec.rb
- spec/models/order_combo_spec.rb
> Controler + Model + Config Membership

- app/assets/javascripts/channels/messages.js
- app/assets/javascripts/custom.js
- app/assets/javascripts/dashboard.js
- app/assets/javascripts/modal.js
- app/assets/javascripts/order_admin.js
- app/assets/stylesheets/custom.scss
- app/controllers/admin/promos_controller.rb
- app/helpers/session_helper.rb
- app/mailers/notifier_mailer.rb
- app/mailers/user_create_order_notifier_mailer.rb
- app/models/order.rb
- app/models/promo.rb
- app/models/supports/order_support.rb
- app/models/supports/promo_support.rb
- app/views/admin/promos/_promo.html.erb
- app/views/combos/_combo.html.erb
- app/views/combos/index.html.erb
- app/views/combos/show.html.erb
- app/views/notifier_mailer/adv_promos.html.erb
- app/views/notifier_mailer/create_order.html.erb
- app/views/notifier_mailer/reject_order.html.erb
- config/locales/en.yml
- db/migrate/20170802011625_remove_columns_in_combo.rb
- db/seeds.rb
- spec/factories/orders.rb
> fix admin/combo and seed and Mailer services add, fix promo

- app/assets/javascripts/bill.js
- app/assets/javascripts/custom.js
- app/assets/javascripts/order.js
- app/assets/stylesheets/color.scss
- app/assets/stylesheets/custom.scss
- app/controllers/admin/membership_coupons_controller.rb
- app/models/membership_coupon.rb
- app/views/admin/bills/show.html.erb
- app/views/admin/membership_coupons/_membership_coupon.html.erb
- app/views/admin/membership_coupons/index.html.erb
- app/views/admin/membership_coupons/index.js.erb
- app/views/admin/orders/_order_info.html.erb
- app/views/admin/orders/_order_item_footer.html.erb
- app/views/admin/orders/show.html.erb
- app/views/layouts/_menu_staff.html.erb
- config/locales/en.yml
- db/migrate/20170803023951_change_status_membersip.rb
- db/schema.rb
> Views, assets Membership 2

- app/assets/javascripts/custom.js
- app/assets/stylesheets/custom.scss
- app/models/supports/dish_support.rb
- app/views/dishes/index.html.erb
- app/views/dishes/show.html.erb
- app/views/layouts/_menu_customer.html.erb
- app/views/layouts/_menu_staff.html.erb
- app/views/layouts/application.html.erb
- app/views/tables/_customer_code.html.erb
- app/views/tables/index.html.erb
> Fix layout(Logo, menu animation, order view)

- app/assets/javascripts/category.js
- app/assets/javascripts/dashboard.js
- app/assets/javascripts/promo.js
- app/assets/stylesheets/custom.scss
- app/controllers/dishes_controller.rb
- app/models/dish.rb
- app/views/admin/categories/_form.html.erb
- app/views/admin/promos/_dishes.html.erb
- app/views/admin/promos/_form.html.erb
- config/locales/en.yml
> Fix select item categories, promos

- app/models/staff.rb
Em sửa lỗi login thứ 7
vì hiện tại bọn em chưa hiện được flash lúc login lỗi nên em chưa cho flash vào, em sẽ thêm vào sau ạ
> Fix invalid hash error when login

- app/assets/javascripts/category.js
- app/assets/javascripts/customer.js
- app/assets/javascripts/modal.js
- app/assets/javascripts/promo.js
- app/assets/stylesheets/custom.scss
- app/controllers/admin/bills_controller.rb
- app/controllers/admin/customers_controller.rb
- app/controllers/dishes_controller.rb
- app/models/combo.rb
- app/models/order.rb
- app/models/supports/admin_bill_support.rb
- app/services/bill_service.rb
- app/views/admin/bills/_bill.html.erb
- app/views/admin/bills/_form.html.erb
- app/views/admin/bills/index.html.erb
- app/views/admin/bills/index.js.erb
- app/views/admin/categories/_form.html.erb
- app/views/admin/customers/_customer.html.erb
- app/views/admin/customers/_modal_customer.html.erb
- app/views/admin/orders/_order.html.erb
- app/views/admin/orders/_order_item.html.erb
- app/views/admin/orders/_order_item_current.html.erb
- app/views/admin/orders/index.js.erb
- app/views/admin/orders/show.html.erb
- app/views/dishes/show.html.erb
- config/locales/en.yml
- db/schema.rb
- db/seeds.rb
1. Thêm phần lịch sử 5 lần order gần đây nhất của Customers
2. Thêm trạng thái của món đã chọn + xóa nút cancel khi món đã được sử dụng
> Fix bill view

- app/views/admin/membership_coupons/index.html.erb
- app/views/admin/order_combos/_form.html.erb
- app/views/admin/order_dishes/_form.html.erb
- app/views/admin/orders/edit.html.erb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/new.html.erb
- app/views/admin/orders/show.html.erb
- app/views/admin/promos/edit.html.erb
- app/views/admin/promos/index.html.erb
- app/views/admin/promos/new.html.erb
- app/views/admin/promos/show.html.erb
- app/views/admin/staffs/edit.html.erb
- app/views/admin/staffs/index.html.erb
- app/views/admin/staffs/new.html.erb
xóa các phần line break không cần thiết sau khi đã sửa header
> Fix header continue

- app/assets/stylesheets/custom.scss
- app/models/ability.rb
- app/views/admin/categories/show.html.erb
- app/views/admin/chef/index.html.erb
- app/views/admin/combos/edit.html.erb
- app/views/admin/combos/index.html.erb
- app/views/admin/combos/new.html.erb
- app/views/admin/combos/show.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/dishes/edit.html.erb
- app/views/admin/dishes/index.html.erb
- app/views/admin/dishes/new.html.erb
- app/views/admin/dishes/show.html.erb
- app/views/combos/_combo.html.erb
- app/views/combos/index.html.erb
- app/views/combos/show.html.erb
- app/views/layouts/_menu_customer.html.erb
- app/views/layouts/_menu_staff.html.erb
- app/views/tables/index.html.erb
- config/locales/en.yml
sửa header để luôn hiện trên màn hình + một vài lỗi view khác:
dashboard -> statistics
admin order: tách ô search với chữ all
button ở combo giờ có thể ấn vào cả nút thay vì phải ấn chữ
> Fix header, view
